### ISSUE TITLE
Exception in DescriptorBuilder for extension with redefines

### ISSUE THREAD

**Issue by fra-pa** [bpmn-io/moddle#38]
Trying to [get type information](https://github.com/fra-pa/moddle/blob/9955c146efdf6513fd1a972c7c6bc109e46c0052/test/spec/extension.js#L55) or [create an instance](https://github.com/fra-pa/moddle/blob/9955c146efdf6513fd1a972c7c6bc109e46c0052/test/spec/extension.js#L65) of a type (`c:CustomRoot`) which `extends` another type (`b:Root`) **and** redefines a property (`b:Root#generic`), the following exception occurs:

```
Error: refined property <b:generic> not found
      at DescriptorBuilder._545‍.r.DescriptorBuilder.redefineProperty (lib/descriptor-builder.js:125:11)
      at DescriptorBuilder.<anonymous> (lib/descriptor-builder.js:219:12)
      at forEach (node_modules/min-dash/dist/index.js:170:20)
      at DescriptorBuilder._545‍.r.DescriptorBuilder.addTrait (lib/descriptor-builder.js:202:3)
      at lib/registry.js:185:13
      at Registry._a72‍.r.Registry.mapTypes (lib/registry.js:165:3)
      at Registry._a72‍.r.Registry.getEffectiveDescriptor (lib/registry.js:184:8)
      at Moddle._a72‍.r.Moddle.getType (lib/moddle.js:97:32)
      at Context.<anonymous> (test/spec/extension.js:58:28)
      at processImmediate (internal/timers.js:461:21)
```
# Why?
`DescriptorBuilder` fails to lookup property `b:Root#generic` in `propertiesByName`, because `b:Root` is not a `superClass` of `c:Base` and therefore not found in the inheritance chain of `c:CustomRoot`.

The model ([base.json](https://github.com/bpmn-io/moddle/blob/v5.0.2/test/fixtures/model/extension/base.json) and [custom.json](https://github.com/bpmn-io/moddle/blob/v5.0.2/test/fixtures/model/extension/custom.json)) used for the test looks something like this:

![redefined-properties-ext-type](https://user-images.githubusercontent.com/8592509/116923753-4d10a200-ac57-11eb-8794-757981d18c77.png)

At runtime, the applied extension of `b:Root` by `c:CustomRoot` transforms the model into:

![redefined-properties-ext-type-b-root](https://user-images.githubusercontent.com/8592509/116923798-5dc11800-ac57-11eb-8da5-3c6d537155cb.png)

Redefining properties of extended types is not explicitly documented, but specified in "[moddle/extension/trait/should refine property](https://github.com/bpmn-io/moddle/blob/cd23a5ffd7fbd7a10725d4807456a942b29d108d/test/spec/extension.js#L63)"
(tests that `b:Root#generic` is of type `c:CustomGeneric`).

The documentation [describes the redefinition of properties](https://github.com/bpmn-io/moddle/blob/v5.0.2/docs/descriptor.md#qualifiers) only for inheritance, not for extension:

```
redefines the property inherited from a super type, overriding name, type and qualifiers
```
# Possible solutions
At first sight, I see two options to resolve this issue:
1. Use `redefines` for both, inheritance and extensions (as it seems to be intended right now). Of course, the bug needs to be fixed and documentation should be updated.
2. Introduce a new keyword (i.e. `overwrites` or `replaces`; `replaces` is already [present in the code](https://github.com/bpmn-io/moddle/blob/cd23a5ffd7fbd7a10725d4807456a942b29d108d/lib/descriptor-builder.js#L214) as a synonym for `redefines`, undocumented but [specified](https://github.com/bpmn-io/moddle/blob/cd23a5ffd7fbd7a10725d4807456a942b29d108d/test/spec/extension.js#L134)) for extensions and keep `redefines` for inheritance only.

Most probably, I miss other options ...

# Proposal
I'd prefere to have two different keywords for inheritance and extension. This
- better communicates the intention of the model
- seperates coding paths and therefore allows easier and better structured implementation
- distinguishs between two different generalization features and 'just feels better' or 'more clean' (may not count as an argument)

Caveat: it's not compatible!

Maybe I don't see the advantage for a dual use of `redefines` but I suggest to first implement option 1 to remove the bug and strive for option 2 with a new issue.

This needs some more effort, but results in a cleaner implementation and offers the path for a smooth migration: keep `redefines` for extensions, mark it as deprecated and remove this option in a later version.

Regards,
Frank

**Comment by fra-pa** [comment]
With a closer look at the code I need to correct myself.

> `replaces` is already present in the code as a synonym for `redefines`

They are similar, but seperate features. `replaces` allows the extending type to redefine **and** rename the property.

A [comment](https://github.com/bpmn-io/moddle/blob/8c46b6fc67d821b25bbec5e92191df49eb6faa29/lib/descriptor-builder.js#L103) states that

> replacing the named property is intentional

The names express their intention and are used for different purposes. As long as I cannot find meaningful substitutions, I reject my proposal.

I still think that it's worth to think about the intermixing of inheritance and extension for types with redefinition and replacement for properties using the same keywords.

Sorry for causing confusion. Feel free to close this issue if the exception is thrown to communicate a misuse.

**Comment by nikku** [comment]
This is a bug unrelated to https://github.com/bpmn-io/moddle/issues/36, right? 

I'd assume getting any type information should never blow up. Instead, the tool should blow up when instantiating the model initially, cf. https://github.com/bpmn-io/moddle/pull/39#discussion_r633347131.

**Comment by nikku** [comment]
`c:CustomRoot` is a _trait_ that extends another property and as such shall not be instantiated. We may (or may not) add a guard to this one day, to throw a more meaningful error message.
